#! /bin/bash
#SBATCH -p q_thesis
#SBATCH -N 32
#SBATCH --ntasks-per-node=32
#SBATCH --cpu-freq=High
#SBATCH --job-name=performanceRun
#SBATCH --time=1:00:00

mkdir ../data/E1

rm ../data/E1/32x32openMPI.txt
echo MPIlib: openMPI
spack load openmpi@4.1.6
make perf
for i in {1..30}; do
    srun ../build/executeExperimentRuns.o runs.json >> ../data/E1/32x32openMPI.txt
echo iteration $i
done
spack unload openmpi@4.1.6 

rm ../data/E1/32x32intelMPI.txt
echo MPIlib: intelMPI
module load mpi/intelmpi
make perf
for i in {1..30}; do
    srun ../build/executeExperimentRuns.o runs.json >> ../data/E1/32x32intelMPI.txt
echo iteration $i
done
module unload mpi/intelmpi

rm ../data/E1/32x32MPICH.txt
echo MPIlib: MPICH
module unload mpi/intelmpi
make perf
for i in {1..30}; do
    mpirun ../build/executeExperimentRuns.o runs.json >> ../data/E1/32x32MPICH.txt
echo iteration $i
done
module unload mpi/intelmpi

echo finished
